import type { Relationship } from "@/app/_lib/types";

// Helper to create dates relative to now
const daysAgo = (days: number): Date => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
};

const yearsAgo = (years: number): Date => {
  const date = new Date();
  date.setFullYear(date.getFullYear() - years);
  return date;
};

export const initialRelationships: Relationship[] = [
  {
    id: 1,
    name: "Mom",
    type: "family",
    strength: 100,
    dunbarLayer: "supportClique",
    reciprocity: "mutual",
    lastInteraction: daysAgo(2),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(30),
    initialIosRating: 7,
    activityDiversity: "diverse",
    interdependence: "intertwined",
    sharedContexts: ["family events", "calls", "visits", "holidays"],
    interactions: [],
  },
  {
    id: 2,
    name: "John (Best Friend)",
    type: "friend",
    strength: 85,
    dunbarLayer: "supportClique",
    reciprocity: "mutual",
    lastInteraction: daysAgo(5),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(10),
    initialIosRating: 6,
    activityDiversity: "diverse",
    interdependence: "moderate",
    sharedContexts: ["gaming", "dinners", "sports", "travel"],
    interactions: [],
  },
  {
    id: 3,
    name: "Sarah (Colleague)",
    type: "acquaintance",
    strength: 70,
    dunbarLayer: "affinityGroup",
    reciprocity: "mutual",
    lastInteraction: daysAgo(3),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(2),
    initialIosRating: 4,
    activityDiversity: "few",
    interdependence: "moderate",
    sharedContexts: ["work", "lunch"],
    interactions: [],
  },
  {
    id: 4,
    name: "Partner",
    type: "significant_other",
    strength: 95,
    dunbarLayer: "supportClique",
    reciprocity: "mutual",
    lastInteraction: daysAgo(0),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(3),
    initialIosRating: 7,
    activityDiversity: "diverse",
    interdependence: "merged",
    sharedContexts: ["home", "dinners", "travel", "hobbies", "family events"],
    interactions: [],
  },
  {
    id: 5,
    name: "Dad",
    type: "family",
    strength: 98,
    dunbarLayer: "supportClique",
    reciprocity: "mutual",
    lastInteraction: daysAgo(4),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(30),
    initialIosRating: 7,
    activityDiversity: "diverse",
    interdependence: "intertwined",
    sharedContexts: ["family events", "calls", "visits", "hobbies"],
    interactions: [],
  },
  {
    id: 6,
    name: "Emily (Sister)",
    type: "family",
    strength: 90,
    dunbarLayer: "supportClique",
    reciprocity: "mutual",
    lastInteraction: daysAgo(7),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(25),
    initialIosRating: 6,
    activityDiversity: "diverse",
    interdependence: "intertwined",
    sharedContexts: ["family events", "calls", "shopping", "travel"],
    interactions: [],
  },
  {
    id: 7,
    name: "David (Old Friend)",
    type: "friend",
    strength: 60,
    dunbarLayer: "sympathyGroup",
    reciprocity: "oneWayInitiator",
    lastInteraction: daysAgo(30),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(15),
    initialIosRating: 5,
    activityDiversity: "few",
    interdependence: "independent",
    sharedContexts: ["occasional meetups", "messages"],
    interactions: [],
  },
  {
    id: 8,
    name: "Michael (Gym Buddy)",
    type: "acquaintance",
    strength: 50,
    dunbarLayer: "affinityGroup",
    reciprocity: "mutual",
    lastInteraction: daysAgo(14),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(1),
    initialIosRating: 3,
    activityDiversity: "single",
    interdependence: "independent",
    sharedContexts: ["gym"],
    interactions: [],
  },
  {
    id: 9,
    name: "Jessica (Work Friend)",
    type: "colleague",
    strength: 75,
    dunbarLayer: "sympathyGroup",
    reciprocity: "mutual",
    lastInteraction: daysAgo(2),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(3),
    initialIosRating: 5,
    activityDiversity: "few",
    interdependence: "moderate",
    sharedContexts: ["work", "lunch", "coffee"],
    interactions: [],
  },
  {
    id: 10,
    name: "Boss",
    type: "colleague",
    strength: 65,
    dunbarLayer: "affinityGroup",
    reciprocity: "oneWayReceiver",
    lastInteraction: daysAgo(1),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(2),
    initialIosRating: 4,
    activityDiversity: "single",
    interdependence: "moderate",
    sharedContexts: ["work"],
    interactions: [],
  },
  {
    id: 11,
    name: "Neighbor (Mrs. Johnson)",
    type: "acquaintance",
    strength: 40,
    dunbarLayer: "activeNetwork",
    reciprocity: "mutual",
    lastInteraction: daysAgo(21),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(5),
    initialIosRating: 2,
    activityDiversity: "single",
    interdependence: "independent",
    sharedContexts: ["neighborhood"],
    interactions: [],
  },
  {
    id: 12,
    name: "Uncle Bob",
    type: "family",
    strength: 80,
    dunbarLayer: "sympathyGroup",
    reciprocity: "mutual",
    lastInteraction: daysAgo(45),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(30),
    initialIosRating: 5,
    activityDiversity: "few",
    interdependence: "independent",
    sharedContexts: ["family events", "holidays"],
    interactions: [],
  },
  {
    id: 13,
    name: "Aunt Lisa",
    type: "family",
    strength: 78,
    dunbarLayer: "sympathyGroup",
    reciprocity: "mutual",
    lastInteraction: daysAgo(30),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(30),
    initialIosRating: 5,
    activityDiversity: "few",
    interdependence: "independent",
    sharedContexts: ["family events", "calls"],
    interactions: [],
  },
  {
    id: 14,
    name: "Cousin Jake",
    type: "family",
    strength: 55,
    dunbarLayer: "affinityGroup",
    reciprocity: "dormant",
    lastInteraction: daysAgo(90),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(25),
    initialIosRating: 4,
    activityDiversity: "single",
    interdependence: "independent",
    sharedContexts: ["family events"],
    interactions: [],
  },
  {
    id: 15,
    name: "Tom (Gaming Buddy)",
    type: "friend",
    strength: 68,
    dunbarLayer: "sympathyGroup",
    reciprocity: "mutual",
    lastInteraction: daysAgo(3),
    createdAt: new Date(),
    relationshipStartDate: yearsAgo(2),
    initialIosRating: 4,
    activityDiversity: "few",
    interdependence: "independent",
    sharedContexts: ["gaming", "discord"],
    interactions: [],
  },
];
